import { IProduct } from '../types/interfaces';

const productList: IProduct[] = [
  {
    id: 1,
    title: 'iPhone 9',
    date: '2022-01-01',
    discount: false,
    brand: 'Apple',
    category: 'smartphones',
    thumbnail: 'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
  },
  {
    id: 2,
    title: 'iPhone X',
    date: '2010-01-01',
    discount: true,
    brand: 'Apple',
    category: 'smartphones',
    thumbnail: 'https://i.dummyjson.com/data/products/2/thumbnail.jpg',
  },
  {
    id: 3,
    title: 'Samsung Universe 9',
    date: '2010-01-01',
    discount: true,
    brand: 'Samsung',
    category: 'smartphones',
    thumbnail: 'https://i.dummyjson.com/data/products/3/thumbnail.jpg',
  },
  {
    id: 4,
    title: 'OPPOF19',
    date: '2010-01-01',
    discount: true,
    brand: 'OPPO',
    category: 'smartphones',
    thumbnail: 'https://i.dummyjson.com/data/products/4/thumbnail.jpg',
  },
  {
    id: 5,
    title: 'Huawei P30',
    date: '2010-01-01',
    discount: true,
    brand: 'Huawei',
    category: 'smartphones',
    thumbnail: 'https://i.dummyjson.com/data/products/5/thumbnail.jpg',
  },
  {
    id: 6,
    title: 'MacBook Pro',
    date: '2010-01-01',
    discount: true,
    brand: 'Apple',
    category: 'laptops',
    thumbnail: 'https://i.dummyjson.com/data/products/6/thumbnail.png',
  },
  {
    id: 7,
    title: 'Samsung Galaxy Book',
    date: '2010-01-01',
    discount: true,
    brand: 'Samsung',
    category: 'laptops',
    thumbnail: 'https://i.dummyjson.com/data/products/7/thumbnail.jpg',
  },
  {
    id: 8,
    title: 'Microsoft Surface Laptop 4',
    date: '2010-01-01',
    discount: true,
    brand: 'Microsoft Surface',
    category: 'laptops',
    thumbnail: 'https://i.dummyjson.com/data/products/8/thumbnail.jpg',
  },
  {
    id: 9,
    title: 'Infinix INBOOK',
    date: '2022-01-01',
    discount: false,
    brand: 'Infinix',
    category: 'laptops',
    thumbnail: 'https://i.dummyjson.com/data/products/9/thumbnail.jpg',
  },
  {
    id: 10,
    title: 'HP Pavilion 15-DK1056WM',
    date: '2022-01-01',
    discount: false,
    brand: 'HP Pavilion',
    category: 'laptops',
    thumbnail: 'https://i.dummyjson.com/data/products/10/thumbnail.jpeg',
  },
];

export default productList;
